config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"

  get "home/about"=>"homes#about"

  # 検索ボタンが押された時
  get "search" => "searches#search"

  # タグ検索
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update]do
    get "daily_posts" => "users#daily_posts"
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end

  # DM
  # resources :messages, only: [:create]
  # resources :rooms, only: [:create,:show]
  get 'message/:id' => 'messages#show', as: 'message'
  resources :messages, only: [:create]

  resources :groups do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ゲストログインのguestメソッド定義
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  # グループ追加
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # フォローする側からのhas_many # 全員分のデータ取得
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :relationships, source: :followed
  # フォローされる側からのhas_many # 全員分のデータ取得
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  # DM関係
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :looks, dependent: :destroy

  # あるユーザーが(user)にフォローされているかを判定するメソッド定義
  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    # ゲストユーザーをログイン状態にする
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    # 投稿数カウント
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  # あるユーザーがフォローしている人を全取得
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  # あるユーザーがフォローされている人を全取得
  def followeds
    @user = User.find(params[:id])
    @users = @user.followeds
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def daily_posts
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  # ゲストユーザーへ
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followers.count %></td>
        <td>フォロワー数:<%= user.followeds.count %></td>
        <td><% if user != current_user %>
              <% if user.is_followed_by?(current_user) %>
                <%= link_to user_relationships_path(user.id), method: :delete do %>
                <p>フォロー外す</p>
                <% end %>
              <% else %>
                <%= link_to user_relationships_path(user.id), method: :post do %>
                <p>フォローする</p>
                <% end %>
              <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followeds.count, followeds_user_path(user) %></th>
  </tr>
</table>

<!--ゲストユーザーがプロフィール編集不可に-->
<div class='row'>
  <% if user == current_user && user.name != "guestuser" %>
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if user.name != "guestuser" %>
      <% if user.is_followed_by?(current_user) %>
        <%= link_to user_relationships_path(user.id), method: :delete do %>
          <button class="btn btn-info">フォロー外す</button>
        <% end %>
      <% else %>
        <%= link_to user_relationships_path(user.id), method: :post do %>
          <button class="btn btn-success">フォローする</button>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class='row mt-2'>
  <% unless user.id == current_user.id %>
    <% if current_user.is_followed_by?(user) && user.is_followed_by?(current_user) %>
      <% if current_user != @user %>
        <%= link_to 'messageを始める', message_path(@user.id)%>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_relationship.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to user_path(user.id) do %>
          <%= image_tag user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followers.count %></td>
        <td>フォロワー数:<%= user.followeds.count %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h4>検索結果</h4>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followeds.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-11'>
      <h2>Follower Users</h2>
      <% if @user.followeds.exists? %>
        <%= render 'relationship', users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-11'>
      <h2>Follow Users</h2>
      <% if @user.followers.exists? %>
        <%= render 'relationship', users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <!--グループへの-->
      <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <%= render 'index',users: @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'daily_posts_form', user: @user %>
      <%= render 'books/chart',books: @books %>
    </div>
  </div>
</div>