config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"

  get "home/about"=>"homes#about"

  # 検索ボタンが押された時
  get "search" => "searches#search"

  # タグ検索
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update]do
    get "daily_posts" => "users#daily_posts"
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end

  # DM
  # resources :messages, only: [:create]
  # resources :rooms, only: [:create,:show]
  get 'message/:id' => 'messages#show', as: 'message'
  resources :messages, only: [:create]

  resources :groups do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  has_many :looks, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  validates :category, presence: true

  # レコードを特定の順序で取得
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
  # いいねの多い順
  scope :popular_books, -> {
   joins(:favorites)
   .where(favorites: { created_at: 1.week.ago..Time.now })
   .group('books.id')
   .order('COUNT(favorites.id) DESC')
  }

  # favorited_by?メソッド
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 閲覧数
  def user_has_look?(user)
    looks.where(user_id: user.id).exists?
  end
  
  # 投稿数カウント
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } 
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } 
  
  # scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  # scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  # scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  # scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  # scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }
  
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
    # 閲覧数をカウントする
    if current_user.name != "guestuser"
      unless Look.where(created_at: Time.zone.now.all_day)
                 .find_by(user_id: current_user.id, book_id: @book.id)
        current_user.looks
                    .create(book_id: @book.id)
      end
    end
  end

  def index
    @book = Book.new

    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:star_count]
      @books = Book.star_count
    elsif params[:popular_books]
      @books = Book.popular_books
    else
      @books = Book.all
    end

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_chart.html.erb
<!--前日比と先週比-->
<h4>投稿数の前日比・前週比</h4>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今日の投稿</th>
          <th>昨日の投稿</th>
          <th>前日比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
      	  <td><%= @today_book.count %></td>
      	  <td><%= @yesterday_book.count %></td>
              <% if @yesterday_book.count == 0 %>
      	  <td>前日の投稿はなし</td>
              <% else %>
      	  <td><% @the_day_before = @today_book.count / @yesterday_book.count %>
      	  <%= (@the_day_before * 100).round %>%</td>
              <% end %>
        </tr>
      </tbody>
    </table>

    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今週の投稿</th>
        <th>先週の投稿</th>
        <th>先週比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
      	  <td><%= @this_week_book.count %></td>
      	  <td><%= @last_week_book.count %></td>
              <% if @last_week_book.count == 0 %>
      	  <td>先週の投稿はなし</td>
              <% else %>
      	  <td><% @the_week_before = @this_week_book.count / @last_week_book.count  %>
      	  <%= (@the_week_before * 100).round %>%</td>
              <% end %>
        </tr>
      </tbody>
    </table>
  </div>

<!--過去7日分-->
<h4>7日間分の投稿数</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>６日前</th>
        <th>５日前</th>
        <th>４日前</th>
        <th>３日前</th>
        <th>２日前</th>
        <th>１日前</th>
        <th>今日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @books.created_days_ago(6).count %></td>
        <td><%= @books.created_days_ago(5).count %></td>
        <td><%= @books.created_days_ago(4).count %></td>
        <td><%= @books.created_days_ago(3).count %></td>
        <td><%= @books.created_days_ago(2).count %></td>
        <td><%= @books.created_days_ago(1).count %></td>
        <td><%= @books.created_today.count %></td>
      </tr>
    </tbody>
  </table>

  <!--chart.js-->
  <canvas id="myLineChart"></canvas>
  <script>
    $(document).ready(function () {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_days_ago(6).count %>,
                <%= @books.created_days_ago(5).count %>,
                <%= @books.created_days_ago(4).count %>,
                <%= @books.created_days_ago(3).count %>,
                <%= @books.created_days_ago(2).count %>,
                <%= @books.created_days_ago(1).count %>,
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

app/views/books/_form.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>error(s) prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  
   <!--starについての記述-->
  <% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;
  
        elem.innerHTML = ""
        let opt = {  
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: book %>
    </div>
  <% end %>
  
  <div class="form-group">
    <label>Category</label>
    <%= f.text_field :category,class: 'form-control book_category' %>
  </div>
  
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td>
          <% if book.category.present? %>
            <%=link_to book.category,tagsearches_search_path(content: book.category) %>
          <% end %>
        </td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
        <td>コメント数:<%= book.book_comments.count %></td>
        <td><%= render "books/static_rate", book: book %></td>
        <td><%= render partial: "books/look", locals: { book: book } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_look.html.erb
<% if current_user && book.user_has_look?(current_user) %>
  <div class="text-danger">
    閲覧数:<%= book.looks.count %>
  </div>
  
<% else %>
  <div class="text-dark">
    閲覧数<%= book.looks.count %>
  </div>
<% end %>

app/views/books/_static_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= book.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(latest: "true") %>
      |<%= link_to '古い順', books_path(old: "true") %>
      |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      |<%= link_to '人気順', books_path(popular_books: "true") %>
      <%= render 'index', books: @books, book: @book %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @newbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr id="book_<%= @book.id %>">
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.category.present? %>
              <%=link_to @book.category,tagsearches_search_path(content: @book.category) %>
            <% end %>
          </td>
          <td><%= render "books/static_rate", book: @book %></td>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
          <td id="comments_index_comments">
            <%= render "book_comments/index_comments", book: @book %>
          </td>
          <td><%= render partial: "books/look", locals: { book: @book } %></td>
        </tr>
      </table>

      <div id="comments_index">
        <%= render "book_comments/index", book: @book %>
      </div>
      <div id="comments_form">
        <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      </div>

    </div>
  </div>
</div>